### ISSUE TITLE
UnityEngine Tooltip attribute doesn't work

### ISSUE THREAD

**Issue by Necka44** [dbrizov/NaughtyAttributes#293] opened 2021-12-28 02:20 UTC
Hello, 
When NaughtyAttributes is in use, the regular [Tooltip("My tooltip text")] doesn't work anymore

Even if the property doesn't use any NaughtyAttributes (but others uses them) the tooltip won't show at all in the inspector.
Simple example:

`[BoxGroup("My Group")]
 [Tooltip("This is an inspector tooltip")]
 public int myInt= 0;`

Is there a way to show tooltips with NaughtyAttributes?

**Comment by dbrizov** [comment] 2022-02-06 16:09
Duplicate of #16

**Closed by dbrizov** 2022-02-06 16:09 UTC
