### ISSUE TITLE
[Required] tag not being ordered properly when using [AllowNesting]

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#150] opened 2020-03-29 01:00 UTC
![image](https://user-images.githubusercontent.com/40035529/77837411-0ce01580-7161-11ea-8025-3092b5610bbd.png)
produces this result
![image](https://user-images.githubusercontent.com/40035529/77837413-136e8d00-7161-11ea-8b25-2f444082b1b4.png)

it should be under 'Item Template'

**Comment by dbrizov** [comment] 2020-03-29 05:57
duplicate of #124

**Closed** 2020-03-29 05:57 UTC
