### ISSUE TITLE
[Bug] Unity 2021.1.x - Package causes components with padding property to not render correctly.

### ISSUE THREAD

**Issue by Gohloum** [dbrizov/NaughtyAttributes#267] opened 2021-09-10 13:41 UTC
Installation of package effects the inspector for controls like UI layouts - HorizontalLayoutGroup, GridLayoutGroup, TextMeshPro, etc.  Anything with padding, the label 'padding' and dropdown arrow appear, but when you click the dropdown, the panel expands and is blank.  The drawer is not rendering the fields.

![Screenshot 2021-09-10 09 40 31](https://user-images.githubusercontent.com/6265945/132862538-bdf12f9e-4bba-498f-b3de-d52651cce1bd.png)

**Comment by dbrizov** [comment] 2021-09-11 16:16
I don't think it's caused by NA. When there are no naughty attributes in use it just draws the default inspector.
I also tested with Unity **2021.1.20f1**, and can't reproduce it. Can you please confirm that it's happening on your side again?

**Comment by dbrizov** [comment] 2021-09-12 11:14
Closing this, because I can't reproduce it

**Closed by dbrizov** 2021-09-12 11:14 UTC
