### ISSUE TITLE
[Request] Enum support for ShowIf/HideIf + EnableIf/DisableIf 

### ISSUE THREAD

**Issue by TrapShooter** [dbrizov/NaughtyAttributes#167] opened 2020-07-05 20:12 UTC
So basically you could say:

public enum Test { OptionA, OptionB, OptionC }
public Test testEnum;

[ShowIfEnum ("testEnum", 1)]
public float health;

I know of another extension class that has this functionality. The link is below, if you read the comments you'll find the enum improvements.

http://www.brechtos.com/hiding-or-disabling-inspector-properties-using-propertydrawers-within-unity-5/

**Comment by Eyap53** [comment] 2020-09-30 11:53
Duplicate of #141 .
It would remove the need to create custom method for each enum just for this, so i believe it may still be useful.

**Comment by dbrizov** [comment] 2021-04-25 05:52
There is a PR for that - #223

**Closed by dbrizov** 2021-04-25 05:52 UTC

**Comment by konsnos** [comment] 2021-05-14 12:43
Do ShowIf/HideIf support multiple Enums or should I create a new request for that? (I'm new to NaughtAttributes. Amazing tool!)

**Comment by dbrizov** [comment] 2021-05-14 15:23
What do you mean by multiple enums? Right now it supports enum values and enum flags (see #217)

**Comment by konsnos** [comment] 2021-05-18 13:11
More like this.
```
public class NaughtyComponent : MonoBehaviour
{
    public EMyEnum enumFlag;

    [ShowIf("enumFlag", EMyEnum.Case0, EMyEnum.Case1)]
    public int enableIfEnum; // Will be shown only if enumFlag == EMyEnum.Case0 or EMyEnum.Case1
}

public enum EMyEnum
{
    Case0,
    Case1,
    Case2
}
```
I've read the documentation of Enum Flags and I think they are something entirely different, isn't it?

**Comment by adamroszyk** [comment] 2021-11-05 11:54
Any progress on this?
Would be amazing to have this feature.
