### ISSUE TITLE
Can't add button in boxGroup

### ISSUE THREAD

**Issue by Pimeko** [dbrizov/NaughtyAttributes#56] opened 2019-04-19 19:00 UTC
Hi,

I'm trying to create a box group with a button inside of it. I try it as follow : 

```C#
    [BoxGroup("Some group")]
    [Button]
    public void SomeMethod()
    {
    }
```

I get the following error : ```The attribute `NaughtyAttributes.BoxGroupAttribute' is not valid on this declaration type. It is valid on `field' declarations only.```

Thanks

**Comment by dbrizov** [comment] 2019-04-21 16:47
I know :(
Currently, buttons can't be inside box groups

**Comment by Pimeko** [comment] 2019-04-21 19:12
All right, thank you for your quick answer and the amazing package!! :)

**Comment by dbrizov** [comment] 2020-02-22 10:37
Duplicate of #97

**Closed by dbrizov** 2020-02-22 10:37 UTC
