### ISSUE TITLE
Can't combine default Unity [Tooltip] attribute and [MinMaxSlider]

### ISSUE THREAD

**Issue by Befezdow** [dbrizov/NaughtyAttributes#210] opened 2021-02-08 22:18 UTC
Tooltip label isn't shown in the inspector when I try to combine these two attributes. Also found this issue: #16.
Strange that it is closed because it is still reproducible.

**Comment by brogan89** [comment] 2021-03-14 06:50
I just discovered this with `ShowIf` as well. 
```csharp
public bool show;
[MinMaxSlider(0, 10), ShowIf(nameof(show))] public Vector2 range; 
[ShowIf(nameof(show))] public float value; 
```
The `value` field will still be showing in the inspector is `show` is false.

**Comment by dbrizov** [comment] 2021-04-24 16:14
Duplicate of #16

**Closed by dbrizov** 2021-04-24 16:14 UTC
