### ISSUE TITLE
ReadOnly very high editor CPU impact

### ISSUE THREAD

**Issue by tabuto74** [dbrizov/NaughtyAttributes#170] opened 2020-08-12 13:58 UTC
With only 5 ReadOnly attributes the editor eat too much cpu and starts to be less responsive. Is there something we can do or it just can't be optimized?

**Comment by dbrizov** [comment] 2020-08-12 14:03
The ReadOnly attribute doesn't do anything, I just put an EditorDisabledScopre there. It's basically 1 call to EditorGUI.PropertyField. That's pretty strange mate. Are you sure it's not something else?

I have reported issued about performance problems, but they are not connected to the ReadOnly attribute. I am currently working on a new release. Will probably release it at the end of the week. Then I will make a second release for the performance issues. I will check the ReadOnly attribute, but it's probably something else.

**Comment by tabuto74** [comment] 2020-08-12 14:10
I was struggling with my classes trying to figure out what was causing the editor lag issue, and after a couple of tries I removed the ReadOnly attributes that fixed the issue.
I'm not sure if it's related to ReadOnly or maybe NaughtAttributes in general. You can just create an empty class and start filling it with variables, then add a few Attrbitues and u'll notice the slowness by urself.

**Comment by dbrizov** [comment] 2020-08-12 14:13
Duplicate of #133

**Closed by dbrizov** 2020-08-12 14:13 UTC
