### ISSUE TITLE
[Bug] Unity 2021 causes default list in inspector to not draw correctly.

### ISSUE THREAD

**Issue by Gohloum** [dbrizov/NaughtyAttributes#265] opened 2021-09-07 13:43 UTC
There seems to be an issue with NaughtyAttributes effecting how lists are rendered in the inspector in 2021 or higher.  The problem is specific when LeanTween is added to a project with NaughtyAttributes.  This error is easy to reproduce by starting a new project in 2021, create a script with a list of objects, and add to a an object in the hierarchy.  Populate the list or add some indexes with empty slots.  Now add LeanTween and NaughtyAttributes packages and then examine the list. You will see that the slots no longer render.  The work around is to use the NaughtyAttributes Reorderable List tag and the list will render.  I have contacted Unity support and they advised contacting you and LeanTween about the issue.

**Comment by Gohloum** [comment] 2021-09-08 02:33
Correction!  The problem exists when adding just about any of the 2D built in packages.   For Instance, adding 2D Animation package will cause the issue to happen. Removing the 2D Animation package does not fix the problem, as it seems I have to remove NaughtyAttributes as well.  So there is definitely some sort of conflict.  

![Screenshot 2021-09-07 22 32 45](https://user-images.githubusercontent.com/6265945/132437024-a43ee63d-b014-4ed7-8467-df542aea57e8.png)

**Comment by Gohloum** [comment] 2021-09-08 02:48
I did a few more tests, and it would seem that in 2021, when you add a package AFTER installing Naughty Attributes, the default List Item renderer in Unity stops drawing correctly.  I was able to trigger this behavior by adding any Unity Registry package after NA was installed as well as several assets from my list.  DOTween, TexturePacker Importer, just to name a few.  So it seems like the re-compile of the packages after an added package sets it off.  The only way I can clear the issue is to remove the packages and NA package, and remove all references in code to NA as well. Then after a compile, Unity's built in list resolves and renders correctly.  Hopefully these conditions will help get you in the right direction.

**Comment by dbrizov** [comment] 2021-09-11 16:14
I just did what you said, and can't reproduce it. I am using Unity **2021.1.20f1**. Can you please confirm that it still happens on your side?
![image](https://user-images.githubusercontent.com/3619573/132954262-2d1a106f-f3fd-4868-a86c-8ff87b6faa64.png)

**Comment by dbrizov** [comment] 2021-09-12 11:14
Closing this, because I can't reproduce it

**Closed by dbrizov** 2021-09-12 11:14 UTC

**Comment by Gohloum** [comment] 2021-09-13 01:46
Hi, 

I was out for the weekend, but I will put project together with the issue and zip and attach it for you so you can see the issue in action.

Thank you for looking into this.

TJ
